import Head from "next/head";
import Image from "next/image";
import BottomBar from "../components/BottomBar";
import HomeCompo from "../components/HomeCompo";
import VideoPlayer from "../components/VideoPlayer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meet Clone</title>
        <meta name="description" content="Generated by create meet clone app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCompo />
      <VideoPlayer />
      <BottomBar />
    </div>
  );
}
